version: '3.8'

services:
  portfolio-application:
    image: ${dockerId:-johnchase}/portfolio-application:${BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-application
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: ${dockerId:-johnchase}/portfolio-static:${BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: ${dockerId:-johnchase}/portfolio-site:${BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-site
    ports:
      - "8080:80"
    depends_on:
      - portfolio-application
      - portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
