version: '3.8'

services:
  portfolio-spring:
    image: ${dockerId:-johnchase}/portfolio-spring:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: simple-service/Dockerfile
      target: portfolio-spring
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-template:
    image: ${dockerId:-johnchase}/portfolio-template:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-template
    depends_on:
      - portfolio-spring
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: ${dockerId:-johnchase}/portfolio-static:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: ${dockerId:-johnchase}/portfolio-site:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-site
    ports:
      - "8080:80"
    depends_on:
      - portfolio-template
      - portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
