version: '3.8'

x-args: &args
  args:
    DOCKER_REGISTRY: ${DOCKER_REGISTRY:-}
    DOCKER_ID: ${DOCKER_ID:-}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  builder-shared-resources:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}builder-shared-resources:latest
    build:
      context: shared-resources
      dockerfile: Dockerfile
      target: builder-shared-resources
    profiles: ["builders"]

  builder-portfolio-simple:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}builder-portfolio-simple:latest
    build:
      context: portfolio-simple
      dockerfile: Dockerfile
      target: builder-portfolio-simple
    profiles: ["builders"]

  portfolio-simple:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}portfolio-simple:${IMAGE_TAG:-latest}
    build:
      context: portfolio-simple
      dockerfile: Dockerfile
      <<: *args
      target: portfolio-simple
    networks:
      - portfolio
    restart: unless-stopped

  builder-portfolio-sql:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}builder-portfolio-sql:latest
    build:
      context: portfolio-sql
      dockerfile: Dockerfile
      target: builder-portfolio-sql
    profiles: ["builders"]

  portfolio-sql:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}portfolio-sql:${IMAGE_TAG:-latest}
    build:
      context: portfolio-sql
      dockerfile: Dockerfile
      <<: *args
      target: portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  builder-portfolio-combined:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}builder-portfolio-combined:latest
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      target: builder-portfolio-combined
    profiles: ["builders"]

  portfolio-template:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}portfolio-template:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-template
    depends_on:
      - portfolio-simple
      - portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}portfolio-static:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: ${DOCKER_REGISTRY}${DOCKER_ID}portfolio-site:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-site
    ports:
      - "8080:80"
    depends_on:
      - portfolio-template
      - portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
