version: '3.8'

services:
  portfolio-application:
    image: portfolio-application
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-application
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: portfolio-static
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-static
    ports:
      - "8080:80"
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: portfolio-site
    build:
      context: .
      dockerfile: ./docker/combined/Dockerfile
      target: portfolio-site
    ports:
      - "8080:80"
    depends_on:
      - portfolio-application
      - portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
