version: '3.8'

x-args: &args
  args:
    REGISTRY: ${REGISTRY:-}
    REPOSITORY: ${REPOSITORY:-}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  builder-portfolio-map:
    image: ${REGISTRY}${REPOSITORY}builder-portfolio-map:${IMAGE_TAG:-latest}
    build:
      context: portfolio-map
      dockerfile: Dockerfile
      <<: *args
      target: builder-portfolio-map

  builder-portfolio-sql:
    image: ${REGISTRY}${REPOSITORY}builder-portfolio-sql:${IMAGE_TAG:-latest}
    build:
      context: portfolio-sql
      dockerfile: Dockerfile
      <<: *args
      target: builder-portfolio-sql

  builder-portfolio-combined:
    image: ${REGISTRY}${REPOSITORY}builder-portfolio-combined:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: builder-portfolio-combined
