version: '3.8'

x-args: &args
  args:
    REGISTRY: ${REGISTRY:-}
    REPOSITORY: ${REPOSITORY:-}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  builder-shared-resources:
    image: ${REGISTRY}${REPOSITORY}builder-shared-resources:${IMAGE_TAG:-latest}
    build:
      context: shared-resources
      dockerfile: Dockerfile
      <<: *args
      target: builder-shared-resources

  builder-portfolio-simple:
    image: ${REGISTRY}${REPOSITORY}builder-portfolio-simple:${IMAGE_TAG:-latest}
    build:
      context: portfolio-simple
      dockerfile: Dockerfile
      <<: *args
      target: builder-portfolio-simple

  portfolio-simple:
    image: ${REGISTRY}${REPOSITORY}portfolio-simple:${IMAGE_TAG:-latest}
    build:
      context: portfolio-simple
      dockerfile: Dockerfile
      <<: *args
      target: portfolio-simple
    networks:
      - portfolio
    restart: unless-stopped

  builder-portfolio-sql:
    image: ${REGISTRY}${REPOSITORY}builder-portfolio-sql:${IMAGE_TAG:-latest}
    build:
      context: portfolio-sql
      dockerfile: Dockerfile
      <<: *args
      target: builder-portfolio-sql

  portfolio-sql:
    image: ${REGISTRY}${REPOSITORY}portfolio-sql:${IMAGE_TAG:-latest}
    build:
      context: portfolio-sql
      dockerfile: Dockerfile
      <<: *args
      target: portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  builder-portfolio-combined:
    image: ${REGISTRY}${REPOSITORY}builder-portfolio-combined:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: builder-portfolio-combined

  portfolio-template:
    image: ${REGISTRY}${REPOSITORY}portfolio-template:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-template
    depends_on:
      - portfolio-simple
      - portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: ${REGISTRY}${REPOSITORY}portfolio-static:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: ${REGISTRY}${REPOSITORY}portfolio-site:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-site
    ports:
      - "8080:80"
    depends_on:
      - portfolio-template
      - portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
