version: '3.8'

x-args: &args
  args:
    REGISTRY: ${REGISTRY:-}
    REPOSITORY: ${REPOSITORY:-}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  portfolio-map:
    image: ${REGISTRY}${REPOSITORY}portfolio-map:${IMAGE_TAG:-latest}
    build:
      context: portfolio-map
      dockerfile: Dockerfile
      <<: *args
      target: portfolio-map
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-sql:
    image: ${REGISTRY}${REPOSITORY}portfolio-sql:${IMAGE_TAG:-latest}
    build:
      context: portfolio-sql
      dockerfile: Dockerfile
      <<: *args
      target: portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-react:
    image: ${REGISTRY}${REPOSITORY}portfolio-react:${IMAGE_TAG:-latest}
    build:
      context: portfolio-react
      dockerfile: Dockerfile
      <<: *args
      target: portfolio-react
    depends_on:
      - portfolio-map
      - portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-template:
    image: ${REGISTRY}${REPOSITORY}portfolio-template:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-template
    depends_on:
      - portfolio-map
      - portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: ${REGISTRY}${REPOSITORY}portfolio-static:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: ${REGISTRY}${REPOSITORY}portfolio-site:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      <<: *args
      target: portfolio-site
    ports:
      - "8080:80"
    depends_on:
      - portfolio-react
      - portfolio-template
      - portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
