version: '3.8'

services:
  portfolio-simple:
    image: ${dockerId:-johnchase}/portfolio-simple:${BUILD_TAG:-local}
    build:
      context: portfolio-simple
      dockerfile: portfolio-simple/Dockerfile
      target: portfolio-simple
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-sql:
    image: ${dockerId:-johnchase}/portfolio-sql:${BUILD_TAG:-local}
    build:
      context: portfolio-sql
      dockerfile: portfolio-sql/Dockerfile
      target: portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-template:
    image: ${dockerId:-johnchase}/portfolio-template:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      target: portfolio-template
    depends_on:
      - portfolio-simple
      - portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: ${dockerId:-johnchase}/portfolio-static:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      target: portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: ${dockerId:-johnchase}/portfolio-site:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: docker/portfolio-combined/Dockerfile
      target: portfolio-site
    ports:
      - "8080:80"
    depends_on:
      - portfolio-template
      - portfolio-static
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
